### PR TITLE
Add support for MFA

### LINKED ISSUE #129: Is 2FA taken into consideration ?
I'm asking and interested to know how you deal with 2FA.

On the other hand i'm encoutering this error : 

Executing: Get activity data for '2023-03-07'

ERROR:__main__:Error occurred: Forbidden url: https://connect.garmin.com/modern/proxy/usersummary-service/usersummary/daily/None

and

ERROR:garminconnect:Login ticket not found (200).

session.json is giving : null

Thanks for your help

### PR DESCRIPTION
**Pull request by cam-rod**
Made a patch for this a while ago, so I got around to formalizing it. Checks if the server requested an MFA code, and if so calls a function to request it from the user. Tested successfully on my account and closes #129 .

Only major drawback is that it requires interactive input, so I used a timed prompt to make sure automated scripts don't get stuck forever.

### CODE REVIEW

**Comment by cuu508** [comment]
FWIW I just tested this, and it worked with my account too.

**Comment by Cloud9Developer** [comment]
I wonder, maybe we can add a wait for the emailed code, pull it, then use that to automate the entire process?

**Comment by cam-rod** [comment]
Sounds like an good idea. It would involve setting up email authentication (ex. generating an app password for Gmail) and grabbing the right email. I don't have time to work on that, but if you want to fork off my branch feel free to do so.

**Comment by Cloud9Developer** [comment]
Retrieving the email and getting the code was easy honestly. I'm working on a withings to garmin sync. Basically merging 2 repos into one (yours and another lol). It's gonna be pretty ugly honestly, but just want it to work haha.

**Comment by cuu508** [comment]
Sorry for offtopic, but, @Cloud9Developer, do you really need to merge the repos together? Couldn't you have a third project, which uses the two libraries as dependencies?

I made a small, quick script that syncs weight data [from Fitbit to Garmin Connect](https://github.com/cuu508/fitbit2gc/). It's a single script, plus `garminconnect` and `fitbit` in `requirements.txt`. (The script nominally works, except due to Garmin's MFA and Fitbit's access tokens expiring, it is hard to automate, which was the whole point)

**Comment by Cloud9Developer** [comment]
What I'm doing is pushing everything to a separate repo to make one project, then later on will reduce it down to more specific code.

For now, I'm just wanting the functionality to work lol

**Comment by matin** [comment]
This can be closed without merging. The current version of `garminconnect` already includes MFA support

**Pull request closed without merging**
