### PR TITLE
Bug fix to session saving example in readme

### PR DESCRIPTION
**Pull request by glgauthier**
Fixed broken try:except statement, implemented saving/loading of session data

### CODE REVIEW

**Comment by cyberjunky** [comment]
@glgauthier thanks man!

**Comment by cyberjunky** [comment]
But to be honest I don't get it, we save the session but still need the email and password, this seems not useful.

**Comment by cyberjunky** [comment]
@glgauthier I have change the API init code, so that the session file can now be supplied without having to supply credentials, and I also used your code in the API example program, thanks again!

**Comment by glgauthier** [comment]
@cyberjunky Sweet! That was the main example I was looking to provide - being able to try login from saved session and prompt for new creds if not. Glad it was useful 👍

**Pull request closed without merging**
