### PR TITLE
Add full steps data

### PR DESCRIPTION
**Pull request by yoedf**
Currently the library support only getting the user summary.
With this PR, we will be able to fetch also the steps and activity level by 15 minutes.
`[{'startGMT': '2020-07-08T07:00:00.0', 'endGMT': '2020-07-08T07:15:00.0', 'steps': 9, 'primaryActivityLevel': 'sedentary', 'activityLevelConstant': True}, {'startGMT': '2020-07-08T07:15:00.0', 'endGMT': '2020-07-08T07:30:00.0', 'steps': 51, 'primaryActivityLevel': 'sedentary', 'activityLevelConstant': True}]`

### CODE REVIEW

**Comment by cyberjunky** [comment]
Great stuff thanks for sharing!

**Comment by yoedfried** [comment]
@cyberjunky Can you create new release?

**Comment by cyberjunky** [comment]
@yoedfried I have created release 0.1.15 on PyPi and GitHub

**Comment by yoedf** [comment]
Thanks 😊

**Pull request merged**
